version: "3"

services:
  dev-web:
    image: nginx:alpine
    container_name: dev-luminexis-web
    volumes:
      - ./public:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - webproxy

networks:
  webproxy:
    external: true
