version: '3'

services:
  web:
    image: nginx:alpine
    container_name: luminexis-web
    volumes:
      - ./public:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - webproxy
    restart: unless-stopped

networks:
  webproxy:
    external: true